### ISSUE TITLE
LilyGo T-Deck support

### ISSUE THREAD

**Issue by svofski** [atomic14/esp32-zxspectrum#2]
Some issues:

 * I'm currently unable to input LOAD "" in 48K mode. What are the key mappings?
 * tap/tzx loading: I only see black screen when I select a tap file
 * 128K tape loader auto-resets

**Comment by svofski** [comment]
I'm pressing G -> Games -> B -> Batty.tzx, Enter
```
g




Listing directory: /fs/

b




Listing directory: /fs/ for files starting with B

Extension: .z80

Extension: .sna

Extension: .tap

Extension: .tzx




Selected /fs/Batty.tzx
Starting new emulator screen

Creating machine

Setting up machine

Loading ROM 16384

Copying ROM 0

Loading tape /fs/Batty.tzx
Loading tape file
File size 32558
tzx_cas_to_wav_size: 12 blocks found
tzx_cas_fill_wave: block 0, block_type 30
Text Description Block (type 30) encountered:
Created with Ramsoft MakeTZX
tzx_cas_fill_wave: block 1, block_type 11
tzx_cas_handle_block: loading 19 bytes
Pause for 583 ms
tzx_cas_fill_wave: block 2, block_type 11
tzx_cas_handle_block: loading 1404 bytes
Pause for 866 ms
tzx_cas_fill_wave: block 3, block_type 11
tzx_cas_handle_block: loading 19 bytes
Pause for 579 ms
tzx_cas_fill_wave: block 4, block_type 11
tzx_cas_handle_block: loading 785 bytes
Pause for 864 ms
tzx_cas_fill_wave: block 5, block_type 11
tzx_cas_handle_block: loading 6914 bytes
Pause for 859 ms
tzx_cas_fill_wave: block 6, block_type 11
tzx_cas_handle_block: loading 4098 bytes
Pause for 870 ms
tzx_cas_fill_wave: block 7, block_type 11
tzx_cas_handle_block: loading 4098 bytes
Pause for 863 ms
tzx_cas_fill_wave: block 8, block_type 11
tzx_cas_handle_block: loading 4098 bytes
Pause for 877 ms
tzx_cas_fill_wave: block 9, block_type 11
tzx_cas_handle_block: loading 4098 bytes
Pause for 866 ms
tzx_cas_fill_wave: block 10, block_type 11
tzx_cas_handle_block: loading 4098 bytes
Pause for 869 ms
tzx_cas_fill_wave: block 11, block_type 11
tzx_cas_handle_block: loading 2678 bytes
Pause for 12335 ms
Total cycles: 840396828
Loading tzx file
tzx_cas_to_wav_size: 12 blocks found
E (70897) ledc: ledc_set_duty(725): LEDC is not initialized

E (70898) ledc: ledc_update_duty(653): LEDC is not initialized

tzx_cas_fill_wave: block 0, block_type 30
Text Description Block (type 30) encountered:
Created with Ramsoft MakeTZX
tzx_cas_fill_wave: block 1, block_type 11
tzx_cas_handle_block: loading 19 bytes
E (70899) ledc: ledc_set_duty(725): LEDC is not initialized

E (70902) ledc: ledc_update_duty(653): LEDC is not initialized

E (70908) ledc: ledc_set_duty(725): LEDC is not initialized

E (70913) ledc: ledc_update_duty(653): LEDC is not initialized

```
this last couple of messages repeats forever

**Comment by cgreening** [comment]
Ah yeah, that's a simple fix.

In the meantime, might be easier to stick to z80 files.

**Comment by svofski** [comment]
Thank you! I could succesfully load Batty and Exolon in 48K mode.

In 128K mode I'm getting a crash while loading (this is Exolon, but I tried other tapes too):
```
ST7789 initialized

Creating folder /fs/snapshots
Running on core: 1

W

1




Creating machine

Setting up machine

Copying ROM 1

Starting machine

Executed at 3.550MHz cycles, frame rate=47.81
Saving 8 memory banks
Recorded time travel instant 1
Free heap: 175576
Free PSRAM: 4272091
Executed at 3.501MHz cycles, frame rate=50.10
Saving 3 memory banks
Recorded time travel instant 2
Free heap: 175232
Free PSRAM: 4272091
Executed at 3.501MHz cycles, frame rate=50.10
Saving 1 memory banks
Recorded time travel instant 3
Free heap: 174852
Free PSRAM: 4272091
Executed at 3.498MHz cycles, frame rate=50.05
Saving 1 memory banks
Recorded time travel instant 4
Free heap: 174472
Free PSRAM: 4272091



ROM loadin

Setting up AySoundListing directory: /fs/

e




Listing directory: /fs/ for files starting with E

Extension: .tap

Extension: .tzx




Selected /fs/Exolon.tzx
Loading tape file into existing emulator screen

Loading tape /fs/Exolon.tzx
Loading tape file
File size 42882
Executed at 0.687MHz cycles, frame rate=9.83
Saving 3 memory banks
Recorded time travel instant 5
Free heap: 172876
Free PSRAM: 4229191
ROM loading routine hit

tzx_cas_to_wav_size: 9 blocks found
tzx_cas_fill_wave: block 0, block_type 32
Archive Info Block (type 32) encountered:
Full title: 
ExolonSoftware house/publisher: 
Hewson ConsultantsAuthor(s): 
Raffaele CeccoYear of publication: 
1987Language: 
EnglishGame/utility type: 
ArcadePrice: 
7.95Protection scheme/loader: 
Hewson IIOrigin: 
Perfect TZX sampled from the original cassette by Church of the Latter-Day SpeccyComment(s): 
CRASH #43; "A well-presented traditional shoot-'em-up with plenty to do and look at" 90% SMASH
Malformed Archive Info Block (Text length different from the declared one).
 Please verify your tape image.
tzx_cas_fill_wave: block 1, block_type 10
tzx_cas_handle_block: loading 19 bytes
ROM loadPause for 1007 ms
tzx_cas_fill_wave: block 2, block_type 10
tzx_cas_handle_block: loading 83 bytes
Pause for 999 ms
tzx_cas_fill_wave: block 3, block_type 10
tzx_cas_handle_block: loading 19 bytes
Pause for 1003 ms
tzx_cas_fill_wave: block 4, block_type 10
tzx_cas_handle_block: loading 770 bytes
ROM loading routine h

Pause for 1008 ms
tzx_cas_fill_wave: block 5, block_type 10
tzx_cas_handle_block: loading 19 bytes
Pause for 1008 ms
tzx_cas_fill_wave: block 6, block_type 10
tzx_cas_handle_block: loading 4098 bytes
ROM loadinPause for 1011 ms
tzx_cas_fill_wave: block 7, block_type 10
tzx_cas_handle_block: loading 19 bytes
Pause for 1003 ms
tzx_cas_fill_wave: block 8, block_type 10
tzx_cas_handle_block: loading 37538 bytes
ROM loading routine hit

ROM loading routine hit

ROMROM lROM loading routine h

ROM loadRding routine hit

ROM loading routine hit

ROM loading routine hit

ROM loading routine h

ROM loaTotal cycles: 928904688
Loading tzx file
tzx_cas_to_wav_size: 9 blocks found
tzx_cas_fill_wave: block 0, block_type 32
Archive Info Block (type 32) encountered:
Full title: 
ExolonSoftware house/publisher: 
Hewson ConsultantsAuthor(s): 
Raffaele CeccoYear of publication: 
1987Language: 
EnglishGame/utility type: 
ArcadePrice: 
7.95Protection scheme/loader: 
Hewson IIOrigin: 
Perfect TZX sampled from the original cassette by Church of the Latter-Day SpeccyComment(s): 
CRASH #43; "A well-presented traditional shoot-'em-up with plenty to do and look at" 90% SMASH
Malformed Archive Info Block (Text length different from the declared one).
 Please verify your tape image.
tzx_cas_fill_wave: block 1, block_type 10
tzx_cas_handle_block: loading 19 bytes
ROM loading routine hit

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED 02h at PC=FF15h.

z80 core: Unknown instruction: ED FFh at PC=FB88h.

z80 core: Unknown instruction: ED FFh at PC=FB88h.

Executed at 1.698MHz cycles, frame rate=0.00
Saving 3 memory banks
Recorded time travel instant 6
Free heap: 170568
Free PSRAM: 4229191
z80 core: Unknown instruction: ED 02h at PC=FE6Ch.

z80 core: Unknown instruction: ED 02h at PC=FE6Ch.

z80 core: Unknown instruction: ED 02h at PC=FE6Ch.

z80 core: Unknown instruction: ED 02h at PC=FE6Ch.

z80 core: Unknown instruction: ED 02h at PC=FE6Ch.

z80 core: Unknown instruction: ED 02h at PC=FE6Ch.

z80 core: Unknown instruction: ED 01h at PC=3C7Fh.

z80 core: Unknown instruction: ED 01h at PC=3C7Fh.

Executed at 0.996MHz cycles, frame rate=0.00
Saving 5 memory banks
Recorded time travel instant 7
Free heap: 170264
Free PSRAM: 4229191
Total execution time: 1.915849s
Total machine time: 4.955429
Wall Clock time: 2.347374s
Speed Up: 2.111052
Progress: 1
Pause for 1007 ms
tzx_cas_fill_wave: block 2, block_type 10
tzx_cas_handle_block: loading 83 bytes
Executed at 0.976MHz cycles, frame rate=0.00
Saving 2 memory banks
Recorded time travel instant 8
Free heap: 169620
Free PSRAM: 4229191
z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=F1FDh.

z80 core: Unknown instruction: ED 00h at PC=F1FDh.

Pause for 999 ms
z80 core: Unknown instruction: ED 00h at PC=71FDh.

z80 core: Unknown instruction: ED 00h at PC=71FDh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

Total execution time: 3.422417s
Total machine time: 9.214375
Wall Clock time: 3.868835s
Speed Up: 2.381693
Progress: 3
z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

tzx_cas_fill_wave: block 3, block_type 10
tzx_cas_handle_block: loading 19 bytes
z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED CBh at PC=DCEDh.

z80 core: Unknown instruction: ED CBh at PC=DCEDh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

Executed at 1.332MHz cycles, frame rate=0.95
Saving 2 memory banks
Recorded time travel instant 9
Free heap: 169252
Free PSRAM: 4229191
z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

Executed at 1.033MHz cycles, frame rate=0.00
Saving 2 memory banks
Recorded time travel instant 10
Free heap: 168884
Free PSRAM: 4229191
z80 core: Unknown instruction: ED 00h at PC=80FEh.

z80 core: Unknown instruction: ED 00h at PC=80FEh.

Total execution time: 5.141785s
Total machine time: 14.095997
Wall Clock time: 5.604441s
Speed Up: 2.515148
Progress: 5
Guru Meditation Error: Core  0 panic'ed (LoadProhibited). Exception was unhandled.



Core  0 register dump:

PC      : 0x420083bb  PS      : 0x00060030  A0      : 0x82005f9f  A1      : 0x3fcc0130  

A2      : 0x3fcb8e70  A3      : 0x0000f7bf  A4      : 0x0000ffff  A5      : 0x3fcb8c00  

A6      : 0x3fcb8bcc  A7      : 0x00005ccd  A8      : 0x00000000  A9      : 0x3fcb8c10  

A10     : 0x00000018  A11     : 0x3d8200f4  A12     : 0x00000017  A13     : 0x000000cb  

A14     : 0xffffff00  A15     : 0x00000001  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  

EXCVADDR: 0x0000001c  LBEG    : 0x40056f5c  LEND    : 0x40056f72  LCOUNT  : 0x00000000  





Backtrace: 0x420083b8:0x3fcc0130 0x42005f9c:0x3fcc0160 0x42025b7b:0x3fcc02c0 0x42025c7d:0x3fcc02f0

  #0  0x420083b8 in Z80Run(Z80Regs*, int) at src/Emulator/z80/opcodes.h:176 (discriminator 4)
  #1  0x42005f9c in ZXSpectrum::runForCycles(int) at src/Emulator/spectrum.h:160

      (inlined by) ZXSpectrum::runForFrame(AudioOutput*, __sFILE*) at src/Emulator/spectrum.cpp:85
  #2  0x42025b7b in Machine::runEmulator() at src/Screens/EmulatorScreen/Machine.cpp:17
  #3  0x42025c7d in runnerTask(void*) at src/Screens/EmulatorScreen/Machine.cpp:8





Core  1 register dump:

PC      : 0x420083bb  PS      : 0x00060130  A0      : 0x820235c7  A1      : 0x3fcace90  

A2      : 0x3fcb8e70  A3      : 0x0000f7bf  A4      : 0x0000ffff  A5      : 0x3fcb8c00  

A6      : 0x3fcb8bcc  A7      : 0x00005ccd  A8      : 0x00000000  A9      : 0x3fcb8c10  

A10     : 0x00000018  A11     : 0x3d8200f4  A12     : 0x00000017  A13     : 0x00000844  

A14     : 0x0000083c  A15     : 0x00000013  SAR     : 0x0000001e  EXCCAUSE: 0x0000001c  

EXCVADDR: 0x0000001c  LBEG    : 0x40056fc5  LEND    : 0x40056fe7  LCOUNT  : 0xffffffff  





Backtrace: 0x420083b8:0x3fcace90 0x420235c4:0x3fcacec0 0x4202c91e:0x3fcacee0 0x4202ce86:0x3fcacf20 0x4202d1b5:0x3fcacf80 0x42023af2:0x3fcacfa0 0x4201f87b:0x3fcad170 0x42020631:0x3fcad1b0 0x42022f85:0x3fcad220 0x4209c247:0x3fcad280 0x4202d97d:0x3fcad2a0 0x4201d012:0x3fcad2c0 0x4201d091:0x3fcad310

  #0  0x420083b8 in Z80Run(Z80Regs*, int) at src/Emulator/z80/opcodes.h:176 (discriminator 4)
  #1  0x420235c4 in ZXSpectrum::runForCycles(int) at src/Screens/EmulatorScreen/../../TZX/../Emulator/spectrum.h:160

      (inlined by) ZXSpectrumTapeListener::runForTicks(unsigned long long) at src/Screens/EmulatorScreen/../../TZX/ZXSpectrumTapeListener.h:42
  #2  0x4202c91e in TzxCas::tzx_cas_handle_block(TapeListener*, unsigned char const*, int, int, int, int, int, int, int, int, int) at src/TZX/tzx_cas.cpp:162 (discriminator 1)
  #3  0x4202ce86 in TzxCas::tzx_cas_do_work(TapeListener*) at src/TZX/tzx_cas.cpp:366
  #4  0x4202d1b5 in TzxCas::load_tzx(TapeListener*, unsigned char*, int) at src/TZX/tzx_cas.cpp:589
  #5  0x42023af2 in GameLoader::loadTape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) at src/Screens/EmulatorScreen/GameLoader.cpp:98
  #6  0x4201f87b in EmulatorScreen::loadTape(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) at src/Screens/EmulatorScreen.cpp:173
  #7  0x42020631 in GameFilePickerScreen::onItemSelect(std::shared_ptr<FileInfo>, int) at src/Screens/GameFilePickerScreen.h:33
  #8  0x42022f85 in PickerScreen<std::shared_ptr<FileInfo> >::pressKey(SpecKeys) at src/Screens/PickerScreen.h:94
  #9  0x4209c247 in NavigationStack::pressKey(SpecKeys) at src/Screens/NavigationStack.h:64
  #10 0x4202d97d in std::_Function_handler<void (SpecKeys), setup()::{lambda(SpecKeys)#2}>::_M_invoke(std::_Any_data const&, SpecKeys&&) at src/main.cpp:170

      (inlined by) _M_invoke at c:\users\svofs\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:297
  #11 0x4201d012 in std::function<void (SpecKeys)>::operator()(SpecKeys) const at c:\users\svofs\.platformio\packages\toolchain-xtensa-esp32s3\xtensa-esp32s3-elf\include\c++\8.4.0\bits/std_function.h:687

      (inlined by) TDeckKeyboard::readKeyboard() at src/Input/TDeckKeyboard.cpp:42
  #12 0x4201d091 in TDeckKeyboard::readKeyboardTask(void*) at src/Input/TDeckKeyboard.cpp:23









ELF file SHA256: 20e932452cdb4a99



Rebooting...

ESP-ROM:esp32s3-20210327

Build:Mar 27 2021

rst:0xc (RTC_SW_CPU_RST),boot:0xe (SPI_FAST_FLASH_BOOT)

Saved PC:0x40377dd0

  #0  0x40377dd0 in esp_restart_noos at /home/runner/work/esp32-arduino-lib-builder/esp32-arduino-lib-builder/esp-idf/components/esp_system/port/soc/esp32s3/system_internal.c:151 (discriminator 1)

SPIWP:0xee

mode:DIO, clock div:1

load:0x3fce3808,len:0x4bc

load:0x403c9700,len:0xbd8

load:0x403cc700,len:0x2a0c

entry 0x403c98d0

Free heap: 263816
Free PSRAM: 8386295
Starting up

Starting up SPI

SPI initialized

[   387][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected

TFTDisplay created

[   393][E][esp32-hal-gpio.c:102] __pinMode(): Invalid pin selected

ST7789 initialized

Creating folder /fs/snapshots
Running on core: 1

```
